### ISSUE TITLE
UEFI compilation

### ISSUE THREAD

**Issue by matanhuji** [ionescu007/SimpleVisor#14]
Hi,

The VS project creates a .sys file by default. A short guide how to generate the efi version (UEFI) would be just great.

**Comment by matanhuji** [comment]
Can someone please help me how to generate the efi version?

**Comment by ionescu007** [comment]
Hi Matan,

Give me a few weeks. I have a PR from someone with the right build information for EDK-II.

**Comment by ionescu007** [comment]
See 42dc94556b1e396251508989ed7168a7f219ade5
