### ISSUE TITLE
Can't build on Windows 8.1

### ISSUE THREAD

**Issue by bocajspear1** [ionescu007/SimpleVisor#17]
I'm trying to build on Windows 8.1. I have the Windows 8.1 WDK installed. I have made no changes to the config other than setting the target to Windows 8.1. When I attempt to build, I get this:
 ```
The command "ml64.exe /c /nologo /Zi /Fo"x64\Optimized\shvosx64.obj" /W3 /errorReport:prompt  /Tant\shvosx64.asm" exited with code 1.
```

I've been messing around for a bit, but I can't get it to work. If I go into a VS command prompt, the command works. I'm using Visual Studio Community Update 3.

**Comment by ionescu007** [comment]
That's strange, looks like there's some sort of bug with the WDK and
assembly files. You should upgrade to the latest WDK and just pick 8.1 as
your target.

Best regards,
Alex Ionescu

**Comment by ionescu007** [comment]
Closing this issue assuming you updated. I don't support old WDKs (you can install WDK 10 for free even on 8.1).
