### ISSUE TITLE
Updating description on HyperPlatform

### ISSUE THREAD

**Issue by tandasat** [ionescu007/SimpleVisor#2]
Hi,

Would you mind updating a description on HyperPlatform in README? While it is true that HyperPlatform suffer from certain complexity comparared with SimpleVisor, it is designed for a research platform and not quite for commercial and/or production usage. 

Also, please let me know if you think HyperPlatform can seen as if it were aiming for production-level use. Since I am one of authors of HyperPlatform, I am very happy with updating a description of HyperPlatform to give a right understanding of the project.

Thank you,

**Comment by ionescu007** [comment]
Hi,

I am happy to change this. I was simply trying to comment on the high quality of the HyperPlatform code and its much better suitability toward production use than SimpleVisor :)

**Comment by ionescu007** [comment]
Also, I realize another point of confusion. When I said "the author", I meant, the author of SimpleVisor -- myself ;-). I changed that part so people don't think it means you.

**Comment by tandasat** [comment]
Thank you for updating the description so quickly!

SimpleVisor is really awesome in a sense of simplicity and readability. I
have to admit that it is better for understanding VT-x for beginners and
update my README to refer to this project for that reason ;)
