### ISSUE TITLE
Run SimpleVisor on Xen

### ISSUE THREAD

**Issue by consen** [ionescu007/SimpleVisor#21]
The Xen supports [Nested Virtualization](https://wiki.xenproject.org/wiki/Nested_Virtualization_in_Xen), that means I can run Xen or KVM hypervisor inside a virtual machine of Xen, however I can't run SimpleVisor on Xen.

Is it able to run SimpleVisor inside a vitual machine of Xen?

**Comment by ionescu007** [comment]
Can you report back why it doesn't work? What failure are you seeing? Are you able to run Hyper-V under Xen?

**Comment by rianquinn** [comment]
Hyper-V doesn't work on Xen natively with 4.9, but there are some patches that we have proposed to [OpenXT](https://github.com/openxt) that provides Hyper-V support for Xen. Does SimpleVisor support VMWare yet? If not, Xen certainly won't work. I know that for KVM we had to play some tricks with the debug registers [Bareflank](http://bareflank.github.io/hypervisor/) as they are not supported in KVM.

**Comment by consen** [comment]
@ionescu007 When I run SimpleVisor inside a virtual machine of Xen, the virtual machines hangs, maybe the Nested Virtualization function is not mature.

**Comment by rianquinn** [comment]
Nested virtualization in Xen is not supported at all, but it does work. SimpleVisor should be able to support it. My guess is it's something silly.

**Comment by ionescu007** [comment]
It definitely works inside of VMWare.

Best regards,
Alex Ionescu
