### ISSUE TITLE
Driver blocked from loading

### ISSUE THREAD

**Issue by pakt** [ionescu007/SimpleVisor#22]
I'm running win7 pro x64 inside vmware. Test signing is on.

```
C:\>sc start sv
[SC] StartService FAILED 1275:

This driver has been blocked from loading
```

What's interesting is that [MemoryMon](https://github.com/tandasat/MemoryMon) works fine:

```
C:\>sc start mm

SERVICE_NAME: mm
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 0
        FLAGS              :
```

Any idea what's the problem?

**Comment by tandasat** [comment]
SimpleVisor does not support Windows 7 as readme states. 

It might not be too hard to run it on Windows 7 though. Try setting "Windows 7" on project properties > Driver Settings > General > Target OS Version. It is not going to compile as-is but minor API replacement might suffice to make it work.

**Comment by pakt** [comment]
It doesn't compile for win7. `MmAllocateContiguousNodeMemory` is not available. 
I changed the Target OS from Windows 10 to Windows 7 in my personal project and it worked. Thanks :+1:
