### ISSUE TITLE
question how works

### ISSUE THREAD

**Issue by publicocean0** [ionescu007/SimpleVisor#26]
hi is there a simple document how works?  Sincerelly except a definition i cant find a mini document explaining how works the mechanism for hypervisor.
Ideally i imagined you define a memory area where you can work , you load the code in that area and if a instruction is trying to go outside there is a trap to a specific function in hypervisor. 
a special trap is used also for instructions with IO accesses. But this is just a my idea.How it is possible to associate a trap to hypervisor for wrong memory access,...?
is there a way for creating a trap in user mode in the memory access?

**Comment by ionescu007** [comment]
Hi!

Sorry for my late reply. If you're actually trying to build real traps/etc, then I suggest you take a look at HyperPlatform or BareFlank. This is more of a 'toy' hypervisor to show the basic/minimal setup.
