### ISSUE TITLE
Question：ShvVmxMtrrAdjustEffectiveMemoryType  Wrong？

### ISSUE THREAD

**Issue by diguoelang** [ionescu007/SimpleVisor#29]
This judgment can guarantee 2M space is within the scope of it?
            if (((LargePageAddress + _2MB) >= VpData->MtrrData[i].PhysicalAddressMin) &&
                (LargePageAddress <= VpData->MtrrData[i].PhysicalAddressMax))
I think It should be：
            if (((LargePageAddress + _2MB) <=  VpData->MtrrData[i].PhysicalAddressMax) &&
                (LargePageAddress >= VpData->MtrrData[i].PhysicalAddressMin))

**Comment by ionescu007** [comment]
The goal is not to check if the page is fully enclosed within the MTRR, but
if _any_ piece of the region touches the MTRR.

Consider:

```    Xs          Xe
              Rs            Re
```

Where `X` is the virtual region, and `R` is the 2MB MTRR space.

Your check would fail because `Xs >= Rs` is FALSE.

Best regards,
Alex Ionescu

**Comment by ionescu007** [comment]
The goal is not to check if the page is fully enclosed within the MTRR, but
if _any_ piece of the region touches the MTRR.

Consider:

```    
        Xs          Xe
              Rs            Re
```

Where `X` is the virtual region, and `R` is the 2MB MTRR space.

Your check would fail because `Xs >= Rs` is FALSE.

Best regards,
Alex Ionescu

**Comment by diguoelang** [comment]
thank you very much, Master @aionescu, You are really my idol.
I have another problem，I've already consulted you on Twitter, I'm afraid you can't see it, send it again here.
I've been researching Microsoft's hypervisor recently, but many windbg commands don't support it. For example, I want to check the physical address memory (like !db). Some fields in VMCS are physical addresses. Can you give me some help? please

**Comment by diguoelang** [comment]
Thank you very much, master @aionescu, You are really my idol.
Recently I have problem, I've already asked you on Twitter, afraid you can't see it. I'll send it again here.
Recently I was studying Hyper-V. I have a problem with debugging vmm(hypervisor).I don't have a good way to distinguish between host and guest on break point.
I want to use VPID in VMCS, but it often changes.
Can you give me some help? please.
