### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by Labuurii** [ionescu007/SimpleVisor#39]
If I understand correctly this hypervisor only supports intel?
Is there any plans to support amd aswell?

**Comment by ionescu007** [comment]
Hyperplatform from Satoshi Tanda (linked on my readme) supports AMD too. At
some point we might merge them.

Best regards,
Alex Ionescu

**Comment by tandasat** [comment]
SimpleSvm supports AMD, and not HyperPlatform. 
https://github.com/tandasat/SimpleSvm

**Comment by Labuurii** [comment]
Ok, thank you :)
