### ISSUE TITLE
Is this line code right?

### ISSUE THREAD

**Issue by CrazyHarb** [ionescu007/SimpleVisor#41]
Hi, the 'shvvmx.c'  line 131. Is the code "ShvOsGetPhysicalAddress(&VpData->Epdpt)"  right ? I think maybe the code "ShvOsGetPhysicalAddress(VpData->Epdpt)" is right. ;)

**Comment by hypervisor** [comment]
No, it’s correct.

**Comment by CrazyHarb** [comment]
> No, it’s correct.

Thank you. I got it.
